name = "Tutu ` S World"
author = "bm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ee03f9d13f9cd29457b42c2acc1eb46a95e1d2cf641cd7efe4d1e2b4b41f6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
