name = "Tutu ` S World"
author = "bm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b346ac218ab108d20ced9221ada2ff58ecacc1a56c8f19df0a4bf5f79ffd651"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
