name = "Tutu ` S World"
author = "bm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f43672af080673cfdd437e89c0f1f58db480eae3f4fe58a46bc84e8cf908038"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
